services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MyStrongPassword2025!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    
  api:
    container_name: myinventory-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__SqlServer: ${SQL_CONNECTION_STRING_ENCRYPTED}
      Crypto__KEY: ${CRYPTO_KEY}
      Crypto__IV: ${CRYPTO_IV}

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    environment:
      MSSQL_SA_PASSWORD: "MyStrongPassword2025!"
    volumes:
      - ../../SQL:/scripts
      - ./Docker/init-db.sh:/init-db.sh
    entrypoint:
      - /bin/bash
      - /init-db.sh

volumes:
  sql_data: