name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore External.MyInventoryApi.sln
      
      - name: Build
        run: dotnet build External.MyInventoryApi.sln --configuration Release --no-restore
      
      - name: Run tests
        run: dotnet test External.MyInventoryApi.sln --configuration Release --no-build --verbosity normal